#!/usr/bin/env python3
"""make_fixture.py -- generate the sample Report BY RUNNING THE ENGINE.

The fixture was hand-written. Within hours the engine grew `basis`,
`materiality` and `share_of_observed_dps` and lost `envelope_ref`, and a page
shipped against the stale shape -- so it could not render `materiality`, which
is the field that says "negligible, do not bother". That is two implementations
diverging silently, between my own fixture and my own engine, which is the exact
failure I had just warned Session B about.

The fix is structural rather than a rule to remember: the fixture is now ENGINE
OUTPUT over a SYNTHETIC LOG. The numbers are invented because the log is
invented; the SHAPE cannot drift, because there is only one producer.
"""
import json, sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from gapengine import gap_engine

# The synthetic log now lives in synthetic_log.py so bundle/parity.py can use the
# same one. See that file's header for why parity stopped reading a real log.
from synthetic_log import build
LINES = build()

rep = gap_engine(LINES, {"character": "EXAMPLE", "trio": ["WAR", "MNK", "SHM"], "level": 50,
                         "source": "SYNTHETIC log generated by fixtures/make_fixture.py"})
rep = {"_fixture": True,
       "_why": ("SYNTHETIC. Generated by running gapengine.py over an invented log, so the "
                "SHAPE is always exactly what the engine emits and cannot drift from it. "
                "The numbers carry no measurement and cannot be wrong."),
       "_never": ("Do not replace these values with figures from a real log, ours or a "
                  "reader's. Regenerate with `python3 fixtures/make_fixture.py` instead."),
       "_regenerate": "python3 fixtures/make_fixture.py",
       # `context` is the ONLY block the engine does not build: gapengine.py:198 passes
       # the caller's dict straight through. So its keys here are THIS SCRIPT's, not the
       # engine's, and `_why`'s "the shape is exactly what the engine emits" does not
       # cover it. A real run may carry only `source`. Declared so a consumer guards
       # them rather than inferring they are guaranteed; fixtures/check_drift.py checks
       # this list against the block and checks the pass-through against the engine.
       "_context_is_caller_supplied": sorted(rep["context"]),
       **rep}
with open("fixtures/sample-report.json", "w") as fh:
    json.dump(rep, fh, indent=1); fh.write("\n")
print(f"lines={len(LINES)} deltas={len(rep['deltas'])} refusals={len(rep['refusals'])}")
for d in rep["deltas"]:
    print(f"  {d['lane']:<12} +{d['value']:>6} DPS  {d.get('share_of_observed_dps')}  {d.get('materiality','')[:34]}")
