#!/usr/bin/env python3
"""make_fixture.py -- generate the sample Report BY RUNNING THE ENGINE.

The fixture was hand-written. Within hours the engine grew `basis`,
`materiality` and `share_of_observed_dps` and lost `envelope_ref`, and a page
shipped against the stale shape -- so it could not render `materiality`, which
is the field that says "negligible, do not bother". That is two implementations
diverging silently, between my own fixture and my own engine, which is the exact
failure I had just warned Session B about.

The fix is structural rather than a rule to remember: the fixture is now ENGINE
OUTPUT over a SYNTHETIC LOG. The numbers are invented because the log is
invented; the SHAPE cannot drift, because there is only one producer.
"""
import json, random, sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from gapengine import gap_engine

# Deterministic, so the fixture is reproducible and a diff means a real change.
rng = random.Random(20260830)
LINES, t = [], 0

def stamp(body):
    global t
    h, m, s = 20 + t // 3600, (t // 60) % 60, t % 60
    LINES.append(f"[Sat Aug 30 {h:02d}:{m:02d}:{s:02d} 2026] {body}")

MOBS = ["a rock golem", "a sand giant", "a dune tarantula"]
stamp("ATTN CLAUDE: EXAMPLE: WAR MNK SHM")
for wave in range(6):
    mob = MOBS[wave % len(MOBS)]
    for beat in range(38):
        t += 1
        # auto-attack: two swings most seconds
        for _ in range(2):
            if rng.random() < 0.62:
                stamp(f"You slash {mob} for {rng.randint(38, 96)} points of damage.")
            else:
                stamp(f"You try to slash {mob}, but miss!")
        # ability lanes, deliberately fired well under their cooldown
        if rng.random() < 0.09:
            stamp(f"You kick {mob} for {rng.randint(14, 34)} points of damage."
                  if rng.random() < 0.65 else f"You try to kick {mob}, but miss!")
        if rng.random() < 0.11:
            stamp(f"You bash {mob} for {rng.randint(16, 40)} points of damage."
                  if rng.random() < 0.6 else f"You try to bash {mob}, but miss!")
        if rng.random() < 0.05:
            stamp(f"You hit {mob} for {rng.randint(180, 240)} points of magic damage "
                  f"by Example Nuke III." + (" (Critical)" if rng.random() < 0.07 else ""))
        if rng.random() < 0.012:
            stamp(f"{mob.capitalize()} resisted your Example Nuke III!")
    stamp(f"You slash {mob} for {rng.randint(38, 96)} points of damage.")
    stamp(f"You have slain {mob}!")
    t += 25   # a gap, so engagements are real runs rather than one block

rep = gap_engine(LINES, {"character": "EXAMPLE", "trio": ["WAR", "MNK", "SHM"], "level": 50,
                         "source": "SYNTHETIC log generated by fixtures/make_fixture.py"})
rep = {"_fixture": True,
       "_why": ("SYNTHETIC. Generated by running gapengine.py over an invented log, so the "
                "SHAPE is always exactly what the engine emits and cannot drift from it. "
                "The numbers carry no measurement and cannot be wrong."),
       "_never": ("Do not replace these values with figures from a real log, ours or a "
                  "reader's. Regenerate with `python3 fixtures/make_fixture.py` instead."),
       "_regenerate": "python3 fixtures/make_fixture.py",
       # `context` is the ONLY block the engine does not build: gapengine.py:198 passes
       # the caller's dict straight through. So its keys here are THIS SCRIPT's, not the
       # engine's, and `_why`'s "the shape is exactly what the engine emits" does not
       # cover it. A real run may carry only `source`. Declared so a consumer guards
       # them rather than inferring they are guaranteed; fixtures/check_drift.py checks
       # this list against the block and checks the pass-through against the engine.
       "_context_is_caller_supplied": sorted(rep["context"]),
       **rep}
with open("fixtures/sample-report.json", "w") as fh:
    json.dump(rep, fh, indent=1); fh.write("\n")
print(f"lines={len(LINES)} deltas={len(rep['deltas'])} refusals={len(rep['refusals'])}")
for d in rep["deltas"]:
    print(f"  {d['lane']:<12} +{d['value']:>6} DPS  {d.get('share_of_observed_dps')}  {d.get('materiality','')[:34]}")
